"""
Ireland Addiction Treatment Access vs Deprivation Analysis — Small Area Edition
===============================================================================
Uses CSO Census 2022 Small Area Population Statistics (SAPS) to build a
custom deprivation composite at Small Area level (~18,500 SAs, 5× finer than
the previous ED-level analysis) joined to CSO 2022 SA boundaries (generalised 20m).

Deprivation composite (custom, SAPS-derived) components — all standardised:
  + unemployment rate (short-term + long-term / economically active)
  + LA renting rate
  + private renting rate
  + low social class rate (unskilled + semi-skilled)
  + low education rate (left school ≤ 15)
  + overcrowding rate
  − owner-occupation rate  (negative = affluent indicator)
Result negated so more negative = more deprived (Pobal sign convention).

Join: SAPS.GUID → SA_boundary.SA_GUID_2022
"""

import os, sys, io, json, math, warnings
import urllib.request, urllib.parse

import numpy as np
import pandas as pd
import geopandas as gpd
from scipy import stats
import folium
from folium.plugins import MarkerCluster

warnings.filterwarnings("ignore")

OUTPUTS = "docs"
os.makedirs(OUTPUTS, exist_ok=True)
CACHE = "cache"
os.makedirs(CACHE, exist_ok=True)

# ── Data URLs ──────────────────────────────────────────────────────────────────
SAPS_URL = (
    "https://www.cso.ie/en/media/csoie/census/census2022/"
    "SAPS_2022_Small_Area_UR_171024.csv"
)
SA_GEOJSON_URL = (
    "https://data-osi.opendata.arcgis.com/api/download/v1/items/"
    "9472cff586d74f2ba3c240d4344c5720/geojson?layers=0"
)
SA_FEATURESERVER = (
    "https://services-eu1.arcgis.com/BuS9rtTsYEV5C0xh/arcgis/rest/services/"
    "SMALL_AREA_2022_Genralised_20m_view/FeatureServer/0"
)


# ── Helpers ───────────────────────────────────────────────────────────────────

def download_file(url, dest, desc=""):
    if os.path.exists(dest):
        print(f"  Cached: {dest}")
        return True
    print(f"  Downloading {desc or url[:80]}...")
    req = urllib.request.Request(url, headers={"User-Agent": "IrelandResearch/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=180) as resp:
            data = resp.read()
        # Detect if the response is a "pending" JSON from the ArcGIS download service
        if b'"status":"Pending"' in data[:200] or b'"status": "Pending"' in data[:200]:
            print("  Download is still being generated by ArcGIS — will use FeatureServer instead.")
            return False
        with open(dest, "wb") as f:
            f.write(data)
        print(f"  Saved {len(data)/1_000_000:.1f} MB → {dest}")
        return True
    except Exception as e:
        print(f"  Download failed: {e}")
        return False


def fetch_sa_boundaries_via_featureserver(dest):
    """Page through ArcGIS FeatureServer to assemble SA boundaries GeoJSON."""
    print("  Fetching SA boundaries via ArcGIS FeatureServer (paging)...")
    features = []
    offset = 0
    batch = 2000
    fields_out = (
        "SA_GUID_2022,SA_PUB2022,SA_GEOGID_2022,COUNTY_ENGLISH,"
        "COUNTY_GAEILGE,CSO_LEA,ED_ID_STR,ED_ENGLISH"
    )
    while True:
        url = (
            f"{SA_FEATURESERVER}/query?"
            f"where=1%3D1&outFields={urllib.parse.quote(fields_out)}"
            f"&resultOffset={offset}&resultRecordCount={batch}"
            f"&returnGeometry=true&geometryPrecision=5&outSR=4326&f=geojson"
        )
        req = urllib.request.Request(url, headers={"User-Agent": "IrelandResearch/1.0"})
        with urllib.request.urlopen(req, timeout=60) as resp:
            chunk = json.loads(resp.read())
        batch_feats = chunk.get("features", [])
        features.extend(batch_feats)
        print(f"    ...fetched {len(features)} SAs so far")
        if len(batch_feats) < batch:
            break
        offset += batch

    geojson = {
        "type": "FeatureCollection",
        "features": features,
    }
    with open(dest, "w") as f:
        json.dump(geojson, f)
    print(f"  Saved {len(features)} SA features → {dest}")


def haversine_matrix(lat1, lon1, lat2_arr, lon2_arr):
    R = 6371.0
    lat1, lon1 = math.radians(lat1), math.radians(lon1)
    lat2 = np.radians(lat2_arr)
    lon2 = np.radians(lon2_arr)
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat / 2)**2 + math.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2)**2
    return R * 2 * np.arcsin(np.sqrt(a))


# ── Step 1: Addiction services ─────────────────────────────────────────────────

def load_services():
    import hrb_scraper
    hrb_scraper.run()
    df = pd.read_csv(hrb_scraper.OUTPUT_FILE).dropna(subset=["lat", "lng"])
    print(f"[1] Loaded {len(df)} addiction treatment services.")
    return df


# ── Step 2: SAPS — build deprivation composite ────────────────────────────────

def load_saps():
    dest = os.path.join(CACHE, "saps_2022_sa.csv")
    download_file(SAPS_URL, dest, "CSO SAPS 2022 (Small Area)")

    print("  Reading SAPS (this may take a moment — 40 MB, 795 columns)...")
    # Read only the columns we need
    useful_cols = [
        "GUID", "GEOGID",
        # Population
        "T1_1AGETT",
        # Employment (T8_1)
        "T8_1_STUT", "T8_1_LTUT",           # unemployed
        "T8_1_WT",                            # at work
        "T8_1_TT",                            # total econ active+inactive
        # Social class (T9_1)
        "T9_1_SST", "T9_1_UST", "T9_1_TT",  # semi-skilled, unskilled, total
        # Education (T10_1): age left school
        "T10_1_LT15T", "T10_1_15T", "T10_1_TT",
        # Housing tenure (T6_3)
        "T6_3_RLAH",   # LA renting (households)
        "T6_3_RPLH",   # Private renting
        "T6_3_OMLH",   # Owner with mortgage
        "T6_3_OOH",    # Owner outright
        "T6_3_TH",     # Total households
        # Overcrowding (T6_8)
        "T6_8_OVD",    # Overcrowded
        "T6_8_T",      # Total
    ]

    df = pd.read_csv(dest, usecols=useful_cols, low_memory=False)
    n = len(df)
    print(f"  Loaded {n} Small Areas.")

    # ── Build rates ────────────────────────────────────────────────────────────
    def safe_rate(num, denom):
        d = pd.to_numeric(denom, errors="coerce").replace(0, np.nan)
        n_ = pd.to_numeric(num, errors="coerce")
        return (n_ / d * 100).clip(0, 100)

    df["unemp_rate"]    = safe_rate(df["T8_1_STUT"] + df["T8_1_LTUT"], df["T8_1_TT"])
    df["la_rent_rate"]  = safe_rate(df["T6_3_RLAH"], df["T6_3_TH"])
    df["prv_rent_rate"] = safe_rate(df["T6_3_RPLH"], df["T6_3_TH"])
    df["owner_rate"]    = safe_rate(df["T6_3_OMLH"] + df["T6_3_OOH"], df["T6_3_TH"])
    df["low_class_rate"]= safe_rate(df["T9_1_SST"]  + df["T9_1_UST"], df["T9_1_TT"])
    df["low_edu_rate"]  = safe_rate(df["T10_1_LT15T"] + df["T10_1_15T"], df["T10_1_TT"])
    df["overcrowd_rate"]= safe_rate(df["T6_8_OVD"], df["T6_8_T"])
    df["pop"]           = pd.to_numeric(df["T1_1AGETT"], errors="coerce")

    # ── Standardise and compose ────────────────────────────────────────────────
    indicators = {
        "unemp_rate":     +1,   # higher → more deprived
        "la_rent_rate":   +1,
        "prv_rent_rate":  +1,
        "low_class_rate": +1,
        "low_edu_rate":   +1,
        "overcrowd_rate": +1,
        "owner_rate":     -1,   # higher → less deprived
    }

    raw = np.zeros(n)
    for col, sign in indicators.items():
        vals = df[col].values.astype(float)
        # z-score ignoring NaN
        z = (vals - np.nanmean(vals)) / (np.nanstd(vals) + 1e-9)
        z = np.where(np.isfinite(z), z, 0.0)
        raw += sign * z

    # Negate so more negative = more deprived (Pobal sign convention)
    df["dep_score"] = -raw

    # Scale to approx Pobal range (observed −45 to +30) via percentile stretch
    p2, p98 = np.nanpercentile(df["dep_score"], [2, 98])
    df["dep_score"] = (df["dep_score"] - np.nanmean(df["dep_score"])) / (
        np.nanstd(df["dep_score"]) + 1e-9
    ) * 7.0  # ≈ scales so ±2σ → ±14, matching Pobal spread

    print(f"  Deprivation score range: "
          f"{df['dep_score'].min():.1f} to {df['dep_score'].max():.1f}")

    # "Very deprived" ≈ below −10 in Pobal; here use the equivalent bottom 5 %ile
    p5 = df["dep_score"].quantile(0.05)
    df["very_deprived_flag"] = df["dep_score"] < p5
    print(f"  Very deprived threshold (P5): {p5:.2f}  "
          f"({df['very_deprived_flag'].sum()} SAs)")

    return df[["GUID", "GEOGID", "pop", "dep_score", "very_deprived_flag"]]


# ── Step 3: SA Boundaries ─────────────────────────────────────────────────────

def load_boundaries():
    dest = os.path.join(CACHE, "sa_boundaries_2022_gen20m.geojson")
    if not os.path.exists(dest):
        ok = download_file(SA_GEOJSON_URL, dest, "SA Boundaries 2022 Generalised 20m")
        if not ok:
            fetch_sa_boundaries_via_featureserver(dest)

    print("  Reading GeoJSON into GeoDataFrame...")
    gdf = gpd.read_file(dest)
    if gdf.crs and gdf.crs.to_epsg() != 4326:
        gdf = gdf.to_crs(epsg=4326)

    # Normalise the join key column name
    # GeoJSON from ArcGIS uses the field names from the FeatureServer query
    if "SA_GUID_2022" not in gdf.columns and "properties" in dir(gdf):
        raise KeyError("SA_GUID_2022 column missing from boundaries GeoDataFrame")

    print(f"[3] Loaded {len(gdf)} SA polygons. "
          f"Columns: {[c for c in gdf.columns if c != 'geometry']}")
    return gdf


# ── Step 4: Join ──────────────────────────────────────────────────────────────

def join_data(gdf, saps):
    # Primary join: SA_GUID_2022 (boundary) = GUID (SAPS)
    merged = gdf.merge(saps, left_on="SA_GUID_2022", right_on="GUID", how="left")
    missing = merged["dep_score"].isna().sum()
    if missing:
        # Fallback: SA_PUB2022 (boundary) = GEOGID (SAPS)
        fallback = saps.set_index("GEOGID")[["dep_score","pop","very_deprived_flag"]]
        no_match_mask = merged["dep_score"].isna()
        for idx, row in merged[no_match_mask].iterrows():
            pub = row.get("SA_PUB2022", "")
            if pub in fallback.index:
                merged.at[idx, "dep_score"]          = fallback.at[pub, "dep_score"]
                merged.at[idx, "pop"]                = fallback.at[pub, "pop"]
                merged.at[idx, "very_deprived_flag"] = fallback.at[pub, "very_deprived_flag"]
        remaining = merged["dep_score"].isna().sum()
        print(f"  After fallback join: {remaining} SAs still unmatched "
              f"(composite/new SAs, expected).")
    else:
        print(f"  All SAs matched on GUID.")

    print(f"[4] Joined data. Rows: {len(merged)}, "
          f"matched: {merged['dep_score'].notna().sum()}")
    return merged


# ── Step 5: Distance to nearest service ───────────────────────────────────────

def calc_distances(gdf, services):
    print("[5] Calculating distances to nearest addiction service...")
    centroids = gdf.geometry.centroid
    clat = centroids.y.values
    clon = centroids.x.values
    slat = services["lat"].values
    slon = services["lng"].values

    n = len(clat)
    min_dist    = np.full(n, np.inf)
    nearest_name = np.empty(n, dtype=object)

    for i in range(n):
        if not np.isfinite(clat[i]) or not np.isfinite(clon[i]):
            min_dist[i] = np.nan
            nearest_name[i] = ""
            continue
        dists = haversine_matrix(clat[i], clon[i], slat, slon)
        idx = int(np.argmin(dists))
        min_dist[i]     = dists[idx]
        nearest_name[i] = services.iloc[idx]["name"]

    gdf = gdf.copy()
    gdf["dist_km"]        = min_dist
    gdf["nearest_service"] = nearest_name
    valid = np.isfinite(min_dist)
    print(f"  Distance range: {min_dist[valid].min():.1f} – {min_dist[valid].max():.1f} km")
    return gdf


# ── Step 6: Flag underserved areas ────────────────────────────────────────────

def flag_underserved(gdf):
    valid = gdf["dep_score"].notna() & gdf["dist_km"].notna()
    scores = gdf.loc[valid, "dep_score"]
    dists  = gdf.loc[valid, "dist_km"]

    dep_threshold  = scores.quantile(0.25)
    dist_threshold = dists.quantile(0.75)

    gdf["high_deprivation"] = gdf["dep_score"] <= dep_threshold
    gdf["far_from_service"] = gdf["dist_km"]  >= dist_threshold
    gdf["underserved"]      = gdf["high_deprivation"] & gdf["far_from_service"]
    gdf["very_deprived"]    = gdf.get("very_deprived_flag", False)

    n_us  = gdf["underserved"].sum()
    n_vd  = gdf["very_deprived"].sum()
    total = len(gdf)
    print(f"[6] Deprivation threshold (Q25): {dep_threshold:.2f}")
    print(f"    Distance threshold  (Q75):  {dist_threshold:.2f} km")
    print(f"    Underserved SAs: {n_us} ({100*n_us/total:.1f}%)")
    print(f"    Very deprived SAs (P5): {n_vd} ({100*n_vd/total:.1f}%)")
    return gdf, dep_threshold, dist_threshold


# ── Step 7: Dublin breakdown ──────────────────────────────────────────────────

def dublin_breakdown(gdf):
    dublin = gdf[gdf["COUNTY_ENGLISH"].str.upper().str.contains("DUBLIN", na=False)].copy()
    if dublin.empty:
        print("[7] No Dublin SAs found.")
        return pd.DataFrame()
    summary = (
        dublin.groupby("CSO_LEA")
        .agg(
            total_sas   = ("SA_GUID_2022", "count"),
            underserved = ("underserved", "sum"),
            pop         = ("pop", "sum"),
        )
        .reset_index()
        .sort_values("underserved", ascending=False)
    )
    print(f"[7] Dublin breakdown across {len(summary)} Local Electoral Areas.")
    return summary


# ── Step 8: Map ───────────────────────────────────────────────────────────────

def _dep_colour(score, s_min, s_max):
    if pd.isna(score):
        return "#aaaaaa"
    t = max(0.0, min(1.0, (score - s_min) / max(s_max - s_min, 1e-9)))
    if t < 0.5:
        r = int(200 + (1 - 2*t) * 55)
        g = int(30  + 2*t * 100)
        b = int(30  + 2*t * 50)
    else:
        r = int(200 - (2*t - 1) * 160)
        g = int(130 + (2*t - 1) * 95)
        b = int(80  + (2*t - 1) * 130)
    return f"#{r:02x}{g:02x}{b:02x}"


def build_map(gdf, services, dep_threshold, dist_threshold):
    print("[8] Building interactive Folium map...")

    s_min = float(gdf["dep_score"].quantile(0.02))
    s_max = float(gdf["dep_score"].quantile(0.98))

    # Build lightweight copy for mapping
    cols = ["SA_GUID_2022", "SA_PUB2022", "COUNTY_ENGLISH", "CSO_LEA",
            "ED_ENGLISH", "dep_score", "dist_km", "nearest_service",
            "pop", "underserved", "very_deprived", "geometry"]
    gm = gdf[[c for c in cols if c in gdf.columns]].copy()

    gm["_colour"]    = gm["dep_score"].apply(lambda s: _dep_colour(s, s_min, s_max))
    gm["_us"]        = gm["underserved"].astype(int)
    gm["dep_str"]    = gm["dep_score"].apply(lambda s: f"{s:.2f}" if pd.notna(s) else "N/A")
    gm["dist_str"]   = gm["dist_km"].apply(lambda d: f"{d:.1f}" if pd.notna(d) else "N/A")
    gm["pop_str"]    = gm["pop"].apply(lambda p: f"{int(p):,}" if pd.notna(p) else "N/A")
    gm["area_name"]  = gm.get("SA_PUB2022", gm.get("ED_ENGLISH", ""))

    m = folium.Map(location=[53.1, -8.0], zoom_start=7, tiles="CartoDB positron")

    # Choropleth (non-underserved)
    dep_grp = folium.FeatureGroup(name="Deprivation Score (all SAs)", show=True)
    folium.GeoJson(
        data=gm[gm["_us"] == 0].__geo_interface__,
        style_function=lambda feat: {
            "fillColor": feat["properties"].get("_colour", "#aaa"),
            "color":     "#333333",
            "weight":    0.2,
            "fillOpacity": 0.68,
        },
        tooltip=folium.GeoJsonTooltip(
            fields=["area_name", "COUNTY_ENGLISH", "dep_str", "dist_str",
                    "nearest_service", "pop_str"],
            aliases=["Small Area:", "County:", "Deprivation Score:",
                     "Dist. to nearest service (km):",
                     "Nearest service:", "Population:"],
            sticky=True,
        ),
    ).add_to(dep_grp)
    dep_grp.add_to(m)

    # Underserved overlay
    us_grp = folium.FeatureGroup(name="⚠ Underserved SAs (deprived + far)", show=True)
    us_data = gm[gm["_us"] == 1]
    if not us_data.empty:
        folium.GeoJson(
            data=us_data.__geo_interface__,
            style_function=lambda _: {
                "fillColor": "#ff4500",
                "color":     "#8b0000",
                "weight":    1.5,
                "fillOpacity": 0.82,
            },
            tooltip=folium.GeoJsonTooltip(
                fields=["area_name", "COUNTY_ENGLISH", "dep_str",
                        "dist_str", "nearest_service", "pop_str"],
                aliases=["⚠ Small Area:", "County:", "Deprivation Score:",
                         "Dist. to nearest service (km):",
                         "Nearest service:", "Population:"],
                sticky=True,
            ),
        ).add_to(us_grp)
    us_grp.add_to(m)

    # Service markers
    svc_grp = folium.FeatureGroup(name="Addiction Treatment Services", show=True)
    cluster = MarkerCluster().add_to(svc_grp)
    for _, svc in services.iterrows():
        tip = (f"<b>{svc['name']}</b><br>Type: {svc.get('type','')}<br>"
               f"County: {svc.get('county','')}<br>Address: {svc.get('address','')}")
        folium.Marker(
            location=[svc["lat"], svc["lng"]],
            tooltip=folium.Tooltip(tip),
            icon=folium.Icon(color="blue", icon="plus-sign", prefix="glyphicon"),
        ).add_to(cluster)
    svc_grp.add_to(m)

    legend_html = f"""
    <div style="position:fixed;bottom:30px;left:30px;z-index:1000;background:white;
                padding:14px 18px;border-radius:8px;border:1px solid #aaa;
                font-family:Arial,sans-serif;font-size:13px;max-width:320px;
                box-shadow:2px 2px 6px rgba(0,0,0,.3);">
      <b>Ireland Addiction Treatment Access<br>vs Deprivation — 2022 (Small Area)</b>
      <hr style="margin:6px 0;">
      <div style="display:flex;align-items:center;margin:4px 0;">
        <span style="background:#c81e1e;width:18px;height:18px;display:inline-block;
                      margin-right:8px;border:1px solid #555;"></span>
        Highly Deprived (score ≤ {dep_threshold:.1f})
      </div>
      <div style="display:flex;align-items:center;margin:4px 0;">
        <span style="background:#4ac6c6;width:18px;height:18px;display:inline-block;
                      margin-right:8px;border:1px solid #555;"></span>
        Less Deprived / Affluent
      </div>
      <div style="display:flex;align-items:center;margin:4px 0;">
        <span style="background:#ff4500;width:18px;height:18px;display:inline-block;
                      margin-right:8px;border:1px solid #8b0000;"></span>
        <b>⚠ Underserved</b> — deprived <i>and</i>
        &gt; {dist_threshold:.1f} km from any service
      </div>
      <div style="display:flex;align-items:center;margin:4px 0;">
        <span style="color:#1f78b4;font-size:18px;margin-right:8px;">✚</span>
        Addiction Treatment Service
      </div>
      <hr style="margin:6px 0;">
      <div style="font-size:11px;color:#555;">
        <b>~18,500 Small Areas</b> (Census 2022 boundaries).<br>
        Deprivation: custom composite from CSO SAPS 2022<br>
        (unemployment, social class, education, housing tenure,
        overcrowding). More negative = more deprived.<br>
        <b>Caveat:</b> GP-based medication-assisted treatment
        (methadone, buprenorphine) is <u>not included</u> in the
        service locations. Access may be better than indicated
        in areas with active GP prescribers.
      </div>
    </div>
    """
    m.get_root().html.add_child(folium.Element(legend_html))
    folium.LayerControl(collapsed=False).add_to(m)

    out = os.path.join(OUTPUTS, "index.html")
    m.save(out)
    print(f"  Map saved → {out}")
    return out


# ── Step 9: Summary stats ─────────────────────────────────────────────────────

def build_summary(gdf, dublin_df):
    print("[9] Building summary statistics...")

    county_col = "COUNTY_ENGLISH"
    county_df = (
        gdf.groupby(county_col, dropna=False)
        .agg(
            total_sas        = ("SA_GUID_2022", "count"),
            underserved_sas  = ("underserved", "sum"),
            very_deprived_sas= ("very_deprived", "sum"),
            total_pop        = ("pop", "sum"),
            avg_dep_score    = ("dep_score", "mean"),
        )
        .reset_index()
        .rename(columns={county_col: "county"})
    )

    # Underserved population: sum pop where underserved=True per county
    us_pop = (
        gdf[gdf["underserved"]]
        .groupby(county_col, dropna=False)["pop"]
        .sum()
        .rename("underserved_pop")
    )
    county_df = county_df.merge(us_pop, left_on="county", right_index=True, how="left")
    county_df["underserved_pop"] = county_df["underserved_pop"].fillna(0)
    county_df["pct_underserved_sas"] = (
        100 * county_df["underserved_sas"] / county_df["total_sas"]
    ).round(1)
    county_df = county_df.sort_values("underserved_pop", ascending=False)

    out = os.path.join(OUTPUTS, "summary.csv")
    county_df.to_csv(out, index=False)
    print(f"  County summary → {out}")

    if not dublin_df.empty:
        dub_out = os.path.join(OUTPUTS, "dublin_lea_breakdown.csv")
        dublin_df.to_csv(dub_out, index=False)
        print(f"  Dublin LEA breakdown → {dub_out}")

    total_pop = gdf.loc[gdf["pop"].notna(), "pop"].sum()
    under_pop = gdf.loc[gdf["underserved"] & gdf["pop"].notna(), "pop"].sum()
    total_sa  = len(gdf)
    print(f"\n  ── National Summary ─────────────────────────────")
    print(f"  Small Areas analysed:           {total_sa:,}")
    print(f"  Total population:               {int(total_pop):,}")
    print(f"  Underserved SAs:                {int(gdf['underserved'].sum()):,}  "
          f"({100*gdf['underserved'].sum()/total_sa:.1f}%)")
    print(f"  Population in underserved SAs:  {int(under_pop):,}  "
          f"({100*under_pop/total_pop:.1f}%)")
    print(f"  Very deprived SAs (P5):         {int(gdf['very_deprived'].sum()):,}")
    print(f"  ─────────────────────────────────────────────────\n")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("=" * 62)
    print("Ireland Addiction Treatment Access vs Deprivation — SA level")
    print("=" * 62)

    services               = load_services()
    saps                   = load_saps()
    gdf                    = load_boundaries()
    gdf                    = join_data(gdf, saps)
    gdf                    = calc_distances(gdf, services)
    gdf, dep_th, dist_th   = flag_underserved(gdf)
    dublin_df              = dublin_breakdown(gdf)
    build_map(gdf, services, dep_th, dist_th)
    build_summary(gdf, dublin_df)

    print("✓ Pipeline complete. Outputs in:", OUTPUTS)


if __name__ == "__main__":
    main()
